version: "3.8"

services:
  angular:
    build:
      context: Frontend

    ports:
      - "4200:4200"

    volumes:
      - "./Frontend:/app"
      - "/app/node_modules"

  express:
    build:
      context: Backend
      target: development
    ports:
      - "3000:3000"
    links:
      - database

    volumes:
      - ./Backend/:/usr/src/app
      - "./Backend/nodemon.json:/home/node/app/nodemon.json"
      - "/usr/src/app/node_modules"

  database:
    image: mongo:7.0.0
    ports:
      - "27017:21017"
    #environment:
    #  MONGO_INITDB_DATABASE: project

  #postgres:
  #  image: postgres
  #  volumes:
  #    - postgres_data:/var/lib/postgresql/data
  #  environment:
  #    POSTGRES_DB: keycloak
  #    POSTGRES_USER: keycloak
  #    POSTGRES_PASSWORD: password

  #keycloak:
  #  build: Keycloak
  #  environment:
  #    DB_VENDOR: POSTGRES
  #    DB_ADDR: postgres
  #    DB_DATABASE: keycloak
  #    DB_USER: keycloak
  #    DB_SCHEMA: public
  #    DB_PASSWORD: password
  #    KEYCLOAK_USER: admin
  #    KEYCLOAK_PASSWORD: Pa55w0rd
  # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
  #JDBC_PARAMS: "ssl=true"
  #  ports:
  #    - 8080:8080
  #  depends_on:
  #    - postgres
