version: "3.8"

services:
  angular:
    build:
      context: Frontend

    ports:
      - "4200:4200"

    volumes:
      - "./Frontend:/app"
      - "/app/node_modules"

  express:
    build:
      context: Backend
      target: development
    ports:
      - "3000:3000"
    links:
      - database

    volumes:
      - ./Backend/:/usr/src/app
      - "./Backend/nodemon.json:/home/node/app/nodemon.json"
      - "/usr/src/app/node_modules"

  database:
    image: mongo:7.0.0
    ports:
      - "27017:27017"
    #environment:
    #MONGO_INITDB_DATABASE: project
    #MONGO_INITDB_ROOT_USERNAME: konrad
    #MONGO_INITDB_ROOT_PASSWORD: test

